# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 3, 20, 14, 32, 1, 510300, tzinfo=utc)),
        ),
    ]
