# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170320_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 3, 20, 14, 35, 26, 224511, tzinfo=utc)),
        ),
    ]
