# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170331_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/assets/user_data/'), upload_to='avatar'),
        ),
    ]
