# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:59
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170331_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=accounts.models.FileField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
